export const posts = [
  {
    type: 'blog', slug: 'from-labs-to-devsecops', title: 'From security labs to DevSecOps: a notebook begins',
    description: 'Connecting hands-on TryHackMe practice, cloud security, and the next chapter in AI & cybersecurity.',
    date: '2026-10-03', tags: ['TryHackMe', 'DevSecOps'],
    sections: [
      { id: 'starting-point', title: 'The starting point', html: `<p>Security learning and infrastructure work meet in the same place: understanding how a system behaves, where it can fail, and what evidence supports a decision. This notebook brings those threads together.</p><p>My background includes AWS infrastructure, Linux administration, GitHub Actions, IAM access controls, and security automation. Alongside that work, I practise on TryHackMe as <a href="https://tryhackme.com/p/cyberhitman">cyberhitman</a>. As of 3 October 2026, the profile shows 290 completed rooms, 53 badges, and a top 1% ranking.</p>` },
      { id: 'lab-to-system', title: 'Connecting the lab to the system', html: `<p>My completed rooms include Introduction to DevSecOps, SSDLC, Dependency Management, and Linux Fundamentals Part 1. They provide a useful set of topics for a notebook that connects security practice with the work of building and maintaining infrastructure.</p><p>A practical way to document a lab is to record four things: the system being studied, the observation, the security implication, and the control that would reduce the risk. That makes a note useful beyond the exercise itself.</p><div class="callout"><strong>A useful lab note answers two questions.</strong><p>What happened, and what would help a defender prevent or detect it?</p></div>` },
      { id: 'automation', title: 'Making checks repeatable', html: `<p>In a university Linux and cloud security laboratory project, our four-person team set up a multi-node EC2 environment, used OpenVAS for vulnerability scans, and reviewed log anomalies with CloudWatch. My role focused on DevSecOps and infrastructure.</p><p>The project included Bash checks for permissions, open ports, and failed logins, plus a hardening runbook. It is the sort of work this notebook will explore: small checks, clear evidence, and documentation that another person can follow.</p>` },
      { id: 'next-chapter', title: 'The next chapter', html: `<p>I am pursuing an MS in AI & Cybersecurity at IIT Patna, as reflected in my current LinkedIn profile. My interests include secure cloud infrastructure, identity management, automation, and AI-driven threat detection.</p><p>This site starts with one blog post and one technical article. Short reference notes will follow as the notebook grows.</p>` }
    ],
    sources: [{ title: 'TryHackMe · cyberhitman', url: 'https://tryhackme.com/p/cyberhitman' }, { title: 'LinkedIn · Satyam Kumar', url: 'https://www.linkedin.com/in/iamsatyam1/' }, { title: 'GitHub · Satyam2003-dev', url: 'https://github.com/Satyam2003-dev' }]
  },
  {
    type: 'article', slug: 'secure-cicd-foundations', title: 'A security checklist for a CI/CD pipeline',
    description: 'Start with permissions, dependencies, credentials, and the boundary between untrusted code and deployment.',
    date: '2026-10-03', tags: ['CI/CD', 'Cloud security'],
    sections: [
      { id: 'trust-boundaries', title: 'Start with trust boundaries', html: `<p>A pipeline turns repository changes into running software. That means it handles more than build commands: it decides which code runs, which dependencies are trusted, and which credentials can reach an environment.</p><p>This article connects the themes of TryHackMe’s Introduction to DevSecOps, SSDLC, and Dependency Management rooms with a practical review checklist. It is a general reference, rather than a room walkthrough or a description of a particular production system.</p><div class="flow" aria-label="Pipeline review stages"><span>Source</span><span aria-hidden="true">→</span><span>Build &amp; check</span><span aria-hidden="true">→</span><span>Review</span><span aria-hidden="true">→</span><span>Deploy</span></div><p>At each stage, ask what input is trusted, what can execute, and what permissions are available.</p>` },
      { id: 'permissions', title: 'Keep permissions narrow', html: `<p>Start the workflow token with read-only repository access, then grant additional permissions to the individual jobs that require them. A check on a pull request should not inherit the permissions of a deployment job.</p><pre><code># Workflow default
permissions:
  contents: read

# Add deployment permissions only to the deploy job
jobs:
  deploy:
    permissions:
      pages: write
      id-token: write</code></pre><p>This fragment illustrates permissions only; it is not a complete workflow. GitHub’s secure-use reference explains why the token should receive the minimum access needed.</p>` },
      { id: 'dependencies', title: 'Review what the build executes', html: `<p>Treat third-party actions and package dependencies as part of the application’s trust boundary. Pin actions to reviewed full commit SHAs, keep dependency lockfiles in version control, and review updates before merging.</p><p>Review how a workflow handles pull requests from forks. Do not combine privileged triggers, secrets, and execution of untrusted pull-request code. Use dependency and vulnerability checks as inputs to a review, with a clear owner for unresolved findings.</p>` },
      { id: 'credentials', title: 'Prefer temporary cloud credentials', html: `<p>For AWS workloads, prefer IAM roles and temporary credentials. When a CI platform supports federation, use a carefully scoped identity trust relationship rather than placing a long-lived AWS key in the repository.</p><p>AWS recommends least-privilege permissions and regular reviews of unused access. Restrict a deployment identity to its intended resources and conditions, and keep production access separate from validation jobs.</p><p>Do not print credentials in logs. Review failure paths too: automatic secret masking does not guarantee that transformed values or tool errors remain private.</p>` },
      { id: 'review-list', title: 'A review before deployment', html: `<ul class="checklist"><li>Does each job have only the permissions it needs?</li><li>Are third-party actions pinned and dependency updates reviewed?</li><li>Can untrusted code reach secrets or a privileged runner?</li><li>Are cloud credentials temporary and their trust conditions scoped?</li><li>Do production changes pass the required review?</li><li>Can the released artifact be traced back to its source commit?</li></ul><p>Keep the answers alongside the workflow. The checklist becomes more useful when each control has an owner, evidence, and a clear response when a check fails.</p>` }
    ],
    sources: [{ title: 'TryHackMe · Introduction to DevSecOps', url: 'https://tryhackme.com/room/introductiontodevsecops' }, { title: 'TryHackMe · SSDLC', url: 'https://tryhackme.com/room/securesdlc' }, { title: 'TryHackMe · Dependency Management', url: 'https://tryhackme.com/room/dependencymanagement' }, { title: 'GitHub · Secure use reference', url: 'https://docs.github.com/en/actions/reference/security/secure-use' }, { title: 'AWS · IAM security best practices', url: 'https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html' }]
  }
];
