import {Github,Linkedin} from '../components/SocialIcons';
import React from 'react';
import {Link} from 'react-router-dom';
import {motion,useReducedMotion} from 'motion/react';
import {ArrowRight,ArrowUpRight,UserRound,Link2,Tags,Mail,Shield,BookOpen,Code2,Cloud,GraduationCap,BrainCircuit,FlaskConical} from 'lucide-react';
import SecurityDoodle from '../components/SecurityDoodle';
import PostCard from '../components/PostCard';
import Topics from '../components/Topics';
import {posts,site} from '../data/site';
export default function Home(){
  const reduced=useReducedMotion();
  return <main id="main" tabIndex={-1}>
    <section className="cinematic-hero">
      <motion.img className="hero-landscape" src="/assets/images/security-hero.webp" alt="" width="2164" height="727" fetchPriority="high" animate={reduced?undefined:{scale:[1,1.035,1]}} transition={{duration:32,repeat:Infinity,ease:'easeInOut'}}/>
      <div className="hero-shade"/>
      <div className="container cinematic-inner">
        <div className="cinematic-copy"><div className="hero-kicker">SECURITY <span>/</span> CLOUD <span>/</span> DEVSECOPS <span>/</span> AI</div><h1>Building secure systems<br/>for a <span className="blue-gradient">brighter tomorrow.</span></h1><p>I’m <strong>Satyam</strong>, a DevSecOps engineer and cybersecurity learner. I write about secure delivery, cloud infrastructure, hands-on labs, and the intersection of AI and security.</p><div className="actions"><Link className="button primary" to="/blog/"><BookOpen size={17}/>Read the blog <ArrowRight size={16}/></Link><Link className="button hero-outline" to="/articles/"><Code2 size={17}/>Explore articles</Link></div><div className="hero-credentials"><span className="status-dot"/>MS in AI &amp; Cybersecurity · IIT Patna</div></div>
        <div className="hero-handnote" aria-hidden="true">Learn deeply.<br/>Build carefully.<br/>Defend<br/>thoughtfully.<svg viewBox="0 0 140 24"><path d="M4 19C44 2 93 4 135 8" fill="none" stroke="currentColor" strokeWidth="1.5"/></svg></div>
      </div>
    </section>
    <div className="container highlights-wrap"><div className="highlights-strip" aria-label="Satyam’s focus and learning highlights">{[[Shield,'Top 1%','TryHackMe · Oct 2026'],[FlaskConical,'290 rooms','Completed · Oct 2026'],[Code2,'DevSecOps','Secure delivery'],[Cloud,'AWS & Linux','Cloud infrastructure'],[GraduationCap,'IIT Patna','MS · AI & Cybersecurity'],[BookOpen,'Writing','Learning in public']].map(([Icon,title,label])=><div className="highlight" key={title}><Icon size={28}/><div><strong>{title}</strong><span>{label}</span></div></div>)}</div></div><div className="container home-content">
      <div className="home-main"><section className="latest-writing"><div className="section-heading"><h2><span className="heading-line"/>Latest writing</h2><Link className="text-link" to="/blog/">View the blog <ArrowRight size={15}/></Link></div><div className="post-grid">{posts.map(post=><PostCard key={post.slug} post={post} featured/>)}</div></section><section className="featured-projects"><div className="section-heading"><h2><span className="heading-line"/>Selected projects</h2><Link className="text-link" to="/about/">Project background <ArrowRight size={15}/></Link></div><div className="compact-project-grid">{[[Shield,'Security automation lab','AWS EC2, OpenVAS, CloudWatch, and Bash hardening audits.',['AWS','Linux','Bash']],[Link2,'LinkTree application','A personal-links app with Google OAuth, MongoDB, and AWS.',['OAuth','MongoDB','AWS']],[BrainCircuit,'MRI classification','A university image-classification project using TensorFlow and Keras.',['Python','TensorFlow','ML']]].map(([Icon,title,description,tags])=><article className="compact-project" key={title}><Icon size={25}/><h3>{title}</h3><p>{description}</p><div className="tags">{tags.map(tag=><span key={tag}>{tag}</span>)}</div></article>)}</div></section><section className="home-topics"><div className="section-heading"><div><div className="eyebrow muted">The notebook, growing one question at a time</div><h2>Areas of exploration.</h2></div><Link className="text-link" to="/notes/">Notes <ArrowRight size={15}/></Link></div><Topics/><p className="notebook-footnote"><span className="status-dot"/>The notes collection is intentionally empty for now. More pages will grow from the labs.</p></section></div>
      <aside className="home-sidebar" aria-label="About Satyam and notebook links"><section className="sidebar-card"><h2><UserRound size={19}/>About me</h2><p>I’m Satyam, a DevSecOps engineer interested in cybersecurity, cloud infrastructure, and AI. I learn by building, testing, and documenting the systems behind the tools.</p><Link className="sidebar-pill" to="/about/">More about Satyam <ArrowRight size={14}/></Link></section><section className="sidebar-card"><h2><Link2 size={19}/>Quick links</h2><div className="quick-links">{[[Github,'GitHub profile',site.links.github],[Linkedin,'LinkedIn',site.links.linkedin],[Shield,'TryHackMe',site.links.tryhackme],[Mail,'Email me',site.links.email]].map(([Icon,label,url])=><a key={label} href={url}><Icon size={16}/><span>{label}</span><ArrowUpRight size={14}/></a>)}</div></section><section className="sidebar-card"><h2><Tags size={19}/>Notebook topics</h2><div className="sidebar-tags">{['Cybersecurity','DevSecOps','AWS','AI security','Linux','Automation'].map(tag=><span key={tag}>{tag}</span>)}</div></section><SecurityDoodle/></aside>
    </div>
  </main>;
}
